#ifndef ERRORS_H
#define ERRORS_H

#define SUCCESS 0
#define SYSTEM_ERROR -1 //errors from std C commands
#define UNSPECIFIED_ERROR -9999 //else case for error codes

//leave -1 for unresolved errors
typedef enum {
    DISK_ERR_DISK_OPEN_FAILED = -2,
    DISK_ERR_DISK_ACCESS_FAILED = -3,
    DISK_ERR_DISK_ACCESS_DENIED = -4,
    DISK_ERR_DISK_INACTIVE = -5,
    DISK_ERR_OPEN_DISK_BAD_ALIGNMENT = -6,
    DISK_ERR_DISK_ARRAY_FULL = -7,
} DiskError;

typedef enum {
    FS_ERR_INSUFFICIENT_FS_SIZE = -50,
    FS_ERR_WRONG_FS_TYPE = -51,
    FS_ERR_SB_CHECKSUM_FAILED = -52,
    FS_ERR_EXISTING_MOUNTED_FS = -53,
    FS_ERR_MOUNTED_FS_INVALID_SUPERBLOCK = -54,
    FS_ERR_MOUNTED_FS_INVALID_ROOT_DIR_INODE = -55,
    FS_ERR_MOUNTED_FS_INVALID_BITMAP = -56,
    FS_ERR_MOUNTED_FS_INVALID_ROOT_DIR = -57,
    FS_ERR_NO_FS_MOUNTED = -58,
    FS_ERR_INVALID_FILENAME = -59,
    FS_ERR_FILE_TABLE_FULL = -60,
    FS_ERR_DIRECTORY_FULL = -61,
    FS_ERR_ACCESSED_OUT_OF_FILE_TABLE_RANGE = -62,
    FS_ERR_FILE_NOT_IN_USE = -63,
    FS_ERR_INVALID_WRITE_SIZE = -64,
    FS_ERR_READ_EOF = -65,
    FS_ERR_INODE_CHECKSUM_FAILED = -66,
    FS_ERR_DATABLOCK_CHECKSUM_FAILED = -67,
    FS_ERR_PROTECTED_INODE = -68,
    FS_ERR_FILE_NOT_FOUND = -69,
    FS_ERR_INVALID_FILE_PERMISSION = -70,
    FS_ERR_INVALID_OFFSET = -71,
    FS_ERR_BITMAP_FULL = -72,

} FSError;

#endif